name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - requests=2.32.3
  - mlflow=2.13.1
  - pip:
      - wandb==0.17.1
      # - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components

      # - git+https://github.com/Sudonuma/end-to-end-MLPipeline.git#egg=wandb-utils&subdirectory=components
